on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: copilot
    steps:
      - name: Login Figma
        uses: actions/github-script@v7
        with:
          script: |
            const response = await fetch('https://api.figma.com/v1/me', {
              headers: {
                'Authorization': `Bearer ${{ secrets.FIGMA_MCP_SERVER_TOKEN }}`,
                'Content-Type': 'application/json'
              }
            });
            
            if (!response.ok) {
              throw new Error(`Figma API request failed: ${response.status} ${response.statusText}`);
            }
            
            const data = await response.json();
            console.log('Figma user authenticated:', data.email);
            
            // Store the token for use in subsequent steps
            core.setSecret('FIGMA_OAUTH_TOKEN');
            core.exportVariable('FIGMA_OAUTH_TOKEN', '${{ secrets.FIGMA_MCP_SERVER_TOKEN }}');
