name: SDS Component CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
      branches: [main]
      
env:
      NODE_VERSION: '24.x'
      
jobs:
      build-and-publish:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: ${{ env.NODE_VERSION }}
              cache: 'npm'
            
          - name: Install dependencies
            run: npm ci
          
          - name: Build application
            run: npm run app:build
          
          - name: Build Storybook
            run: npm run storybook:build
          
          - name: Run tests (if any)
            run: npm test --if-present
          
          - name: Install Figma Code Connect CLI
            run: npm install -g @figma/code-connect
          
          - name: Publish to Figma Code Connect
            run: |
              figma connect publish \
                  --token ${{ secrets.FIGMA_ACCESS_TOKEN }}